# Generated by Django 5.0 on 2023-12-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='otpdevice',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='OTPDevice',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
